name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run npm install
      run: npm install
    - name: Run unit test
      run: npm test
