name: CI

on: 
  push:
    branches:    
      - master  

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - uses: fifsky/ssh-action@master
      with:
        command: |
          cd /home/build/site/pharmOS/ocelot-staging
          ls -a
        host: ${{ secrets.HOST }}
        user: ubuntu
        key: ${{ secrets.PRIVATE_KEY}}
