name: CI

on: 
  push:
    branches:    
      - master  

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: npm install
    - run: CI=true npm test
    - run: npm run build

    - name: Remove old build files
      uses: fifsky/ssh-action@master
        with:
          command: |
            rm -rf /home/build/site/pharmOS/ocelot-staging/
            ls -a /home/build/site/pharmOS/ocelot-staging/
          host: ${{ secrets.HOST }}
          user: ubuntu
          key: ${{ secrets.PRIVATE_KEY}}
    
    - name: Copy files via ssh key
      uses: appleboy/scp-action@master
      env:
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        KEY: ${{ secrets.PRIVATE_KEY }}
      with:
        source: build/
        target: "/home/build/site/pharmOS/ocelot-staging/"
        strip_components: 1


